/**
 * TradeOps Environment Manifest — derived from repository scan (not speculative).
 *
 * Sources:
 * - process.env / env.* usage across apps, packages, scripts
 * - @tradeops/config domain modules (AI, security, capital, financial gates)
 * - Boot path: apps/api main (loadEnv + assertSecurityBoot + assertProductionEnv)
 *
 * Rules:
 * - Secrets never appear as values here or in docs.
 * - Tenant merchant credentials → encrypted connector vault (not global .env in multi-tenant prod).
 * - Compromised/chat-pasted keys must be rotated; never commit.
 */

export type EnvStorage = 'platform_env' | 'tenant_connector_vault' | 'browser_public' | 'os_only';

export type EnvVarManifest = {
  name: string;
  subsystem: string;
  secret: boolean;
  requiredInProduction: boolean;
  serverOnly: boolean;
  storage: EnvStorage;
  description: string;
  aliases?: string[];
  deprecated?: boolean;
  replacement?: string;
  safeDefault?: string;
};

function v(
  name: string,
  subsystem: string,
  opts: Omit<EnvVarManifest, 'name' | 'subsystem'>,
): EnvVarManifest {
  return { name, subsystem, ...opts };
}

/**
 * Canonical platform variables used by code paths today.
 */
export const PLATFORM_ENV_MANIFEST: EnvVarManifest[] = [
  // ─── Core runtime ─────────────────────────────────────────────
  v('NODE_ENV', 'core', {
    secret: false,
    requiredInProduction: true,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Node environment: development | test | production',
    safeDefault: 'development',
  }),
  v('LOG_LEVEL', 'core', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Pino log level',
    safeDefault: 'info',
  }),
  v('API_PORT', 'core', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'API listen port',
    safeDefault: '4000',
  }),
  v('API_HOST', 'core', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'API bind host (prefer 127.0.0.1 locally)',
    safeDefault: '127.0.0.1',
  }),
  v('WEB_PORT', 'core', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Web listen port',
    safeDefault: '3000',
  }),
  v('WEB_HOST', 'core', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Web bind host',
    safeDefault: '127.0.0.1',
  }),
  v('WEB_ORIGIN', 'core', {
    secret: false,
    requiredInProduction: true,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Browser origin for CORS and cookies',
    safeDefault: 'http://localhost:3000',
  }),
  v('API_PUBLIC_URL', 'core', {
    secret: false,
    requiredInProduction: true,
    serverOnly: false,
    storage: 'platform_env',
    description: 'Public API base URL (SSR + scripts)',
    safeDefault: 'http://127.0.0.1:4000',
  }),
  v('NEXT_PUBLIC_API_PUBLIC_URL', 'core', {
    secret: false,
    requiredInProduction: false,
    serverOnly: false,
    storage: 'browser_public',
    description: 'Browser-visible API base URL',
    safeDefault: 'http://127.0.0.1:4000',
  }),
  v('API_TIMEOUT_MS', 'core', {
    secret: false,
    requiredInProduction: false,
    serverOnly: false,
    storage: 'platform_env',
    description: 'HTTP client timeout for API calls',
    safeDefault: '60000',
  }),
  v('NEXT_PUBLIC_API_TIMEOUT_MS', 'core', {
    secret: false,
    requiredInProduction: false,
    serverOnly: false,
    storage: 'browser_public',
    description: 'Browser API timeout',
    safeDefault: '60000',
  }),
  v('NEXT_PUBLIC_SITE_URL', 'core', {
    secret: false,
    requiredInProduction: false,
    serverOnly: false,
    storage: 'browser_public',
    description: 'Public site URL for metadata / marketing',
  }),

  // ─── Database / cache / local DB tooling ──────────────────────
  v('DATABASE_URL', 'database', {
    secret: true,
    requiredInProduction: true,
    serverOnly: true,
    storage: 'platform_env',
    description: 'PostgreSQL connection string (Prisma)',
  }),
  v('REDIS_URL', 'cache', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Redis URL for cache/queues (optional locally)',
    safeDefault: 'redis://localhost:6379',
  }),
  v('PRISMA_DEV_DB_PORT', 'database', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'os_only',
    description: 'Local Prisma Dev / PGlite TCP port',
    safeDefault: '51214',
  }),
  v('PRISMA_DEV_NAME', 'database', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'os_only',
    description: 'Local Prisma Dev server name',
    safeDefault: 'tradeops',
  }),
  v('EMBEDDED_PG_PORT', 'database', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'os_only',
    description: 'Legacy embedded Postgres port (scripts)',
  }),

  // ─── Security / sessions ──────────────────────────────────────
  v('APP_SECRET', 'security', {
    secret: true,
    requiredInProduction: true,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Session/cookie signing secret (min 16 chars; use long random in prod)',
  }),
  v('CREDENTIALS_MASTER_KEY', 'security', {
    secret: true,
    requiredInProduction: true,
    serverOnly: true,
    storage: 'platform_env',
    description: 'AES master key for encrypting tenant connector credentials',
  }),
  v('SESSION_TTL_HOURS', 'security', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Session lifetime hours',
    safeDefault: '168',
  }),
  v('TRADEOPS_SECURITY_BOOT', 'security', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Security boot mode: hard (default) | warn',
  }),
  v('TRADEOPS_ENV_VALIDATION', 'security', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Env validation: hard (default) | warn',
  }),
  v('TRADEOPS_ALLOW_INSECURE_BIND', 'security', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Allow non-loopback bind with weak secrets (dangerous)',
  }),
  v('TRADEOPS_ALLOW_PUBLIC_FOUNDER', 'security', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Allow founder_direct when publicly bound',
  }),

  // ─── Access / multi-tenancy ───────────────────────────────────
  v('TRADEOPS_ACCESS_MODE', 'tenancy', {
    secret: false,
    requiredInProduction: true,
    serverOnly: true,
    storage: 'platform_env',
    description: 'founder_direct | authenticated | multi_tenant',
    safeDefault: 'founder_direct',
  }),
  v('NEXT_PUBLIC_TRADEOPS_ACCESS_MODE', 'tenancy', {
    secret: false,
    requiredInProduction: false,
    serverOnly: false,
    storage: 'browser_public',
    description: 'Public access-mode hint for UI',
  }),
  v('AUTH_BYPASS', 'tenancy', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Dev synthetic identity (never enable as production multi-tenant auth)',
    safeDefault: 'true',
  }),
  v('TRADEOPS_PUBLIC_WARNING', 'tenancy', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Force founder-direct public deployment warning',
  }),
  v('TRADEOPS_PRODUCTION_WORKSPACE', 'tenancy', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Mark workspace as production-class for gating',
  }),

  // ─── AI runtime — Cohere code-first (canonical) ───────────────
  v('AI_PROVIDER', 'ai', {
    secret: false,
    requiredInProduction: true,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Primary LLM: cohere | openai | xai | gemini | auto',
    safeDefault: 'cohere',
  }),
  v('AI_RUNTIME_ENABLED', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Master switch for AI runtime',
    safeDefault: 'true',
  }),
  v('COHERE_API_KEY', 'ai', {
    secret: true,
    requiredInProduction: true,
    serverOnly: true,
    storage: 'platform_env',
    description:
      'Cohere API key (server-only). Never NEXT_PUBLIC. Rotate if ever pasted in chat.',
  }),
  v('COHERE_BASE_URL', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Cohere API base URL',
    safeDefault: 'https://api.cohere.com',
  }),
  v('COHERE_CHAT_MODEL', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Chat / agent model id',
    safeDefault: 'command-a-03-2025',
    aliases: ['COHERE_MODEL'],
  }),
  v('COHERE_EMBED_MODEL', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Embedding model for retrieval',
    safeDefault: 'embed-v4.0',
  }),
  v('COHERE_RERANK_MODEL', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Rerank model',
    safeDefault: 'rerank-v3.5',
  }),
  v('COHERE_TEMPERATURE', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Default generation temperature',
    safeDefault: '0.2',
  }),
  v('COHERE_MAX_TOKENS', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Default max output tokens',
    safeDefault: '4000',
  }),
  v('COHERE_TIMEOUT_MS', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Provider request timeout ms',
    safeDefault: '60000',
    aliases: ['COHERE_REQUEST_TIMEOUT_MS'],
  }),
  v('COHERE_MAX_RETRIES', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Provider retry count',
    safeDefault: '2',
  }),
  v('COHERE_RETRIEVAL_ENABLED', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Enable Cohere embed/rerank retrieval path',
    safeDefault: 'true',
    aliases: ['RETRIEVAL_ENABLED'],
  }),
  v('AI_STRUCTURED_OUTPUT_ENABLED', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'JSON-schema synthesis for agent loop',
    safeDefault: 'true',
  }),
  v('AI_TOOL_CALLING_ENABLED', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Tool selection phase in agent loop',
    safeDefault: 'true',
  }),
  v('AI_STREAMING_ENABLED', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Streaming responses (progressive)',
    safeDefault: 'true',
  }),
  v('AI_TEXT_OUTPUT_ENABLED', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Include human text in envelope',
    safeDefault: 'true',
  }),
  v('AI_RESPONSE_MODE', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'json_schema | json_object | text',
    safeDefault: 'json_schema',
  }),
  v('AI_OUTPUT_SCHEMA_VERSION', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Canonical envelope schema version',
    safeDefault: '1.0',
  }),
  v('AI_MAX_TOOL_ROUNDS', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Agent tool-selection rounds',
    safeDefault: '8',
  }),
  v('AI_MAX_TOOL_CALLS', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Max tools per request',
    safeDefault: '15',
  }),
  v('AI_MAX_EXECUTION_SECONDS', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Wall-clock budget for agent loop',
    safeDefault: '120',
  }),
  v('AI_REQUIRE_APPROVAL_FOR_WRITES', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Gate write capabilities',
    safeDefault: 'true',
  }),
  v('AI_REQUIRE_APPROVAL_FOR_PAYMENTS', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Gate payment actions',
    safeDefault: 'true',
  }),
  v('AI_REQUIRE_APPROVAL_FOR_REFUNDS', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Gate refunds',
    safeDefault: 'true',
  }),
  v('AI_REQUIRE_APPROVAL_FOR_PUBLISHING', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Gate listing publish',
    safeDefault: 'true',
  }),
  v('AI_INCLUDE_TEXT_OUTPUT', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Envelope include text',
    safeDefault: 'true',
  }),
  v('AI_INCLUDE_JSON_OUTPUT', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Envelope include JSON artifact',
    safeDefault: 'true',
  }),
  v('AI_INCLUDE_EVIDENCE', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Envelope include evidence array',
    safeDefault: 'true',
  }),
  v('AI_INCLUDE_ACTIONS', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Envelope include proposed actions',
    safeDefault: 'true',
  }),
  v('AI_INCLUDE_CONFIDENCE', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Envelope include confidence',
    safeDefault: 'true',
  }),
  v('AI_PROMPT_VERSION', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Optional prompt registry version pin',
  }),
  v('AI_RESPONSE_CACHE_ENABLED', 'ai', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Cache AI responses (default off while validating live path)',
    safeDefault: 'false',
  }),
  v('ENABLE_SIMULATION_MODE', 'ops', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Explicit simulation only — never auto after provider failure',
    safeDefault: 'false',
  }),
  v('TRADEOPS_SIMULATION_MODE', 'ops', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Legacy simulation flag',
    safeDefault: 'false',
  }),
  v('TRADEOPS_ALLOW_PRODUCTION_SIMULATION', 'ops', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Required to allow simulation when NODE_ENV=production',
  }),
  v('NEXT_PUBLIC_TRADEOPS_SIMULATION_MODE', 'ops', {
    secret: false,
    requiredInProduction: false,
    serverOnly: false,
    storage: 'browser_public',
    description: 'UI simulation banner',
  }),

  // ─── Live product projection (SSE) ────────────────────────────
  v('LIVE_PROJECTION_ENABLED', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Enable progressive live product projection pipeline',
    safeDefault: 'true',
  }),
  v('LIVE_PROJECTION_TRANSPORT', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'sse (default) | websocket (future)',
    safeDefault: 'sse',
  }),
  v('LIVE_PROJECTION_MAX_SOURCES', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Max concurrent source adapters per live query',
    safeDefault: '6',
  }),
  v('LIVE_PROJECTION_MAX_ITEMS', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Max items projected per live query',
    safeDefault: '50',
  }),
  v('LIVE_PROJECTION_TIMEOUT_MS', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Wall-clock budget for a live projection query',
    safeDefault: '120000',
  }),

  // ─── Search (TradeOps Search Manager) ─────────────────────────
  v('WEB_SEARCH_ENABLED', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Master switch for public web search',
    safeDefault: 'false',
  }),
  v('SEARCH_PROVIDER_PRIMARY', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'openai | tavily | xai',
    safeDefault: 'openai',
    aliases: ['WEB_SEARCH_PROVIDER'],
  }),
  v('SEARCH_PROVIDER_RETRIEVAL', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Retrieval preference',
    safeDefault: 'openai',
  }),
  v('SEARCH_PROVIDER_INTERNAL', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'cohere | local internal retrieval',
    safeDefault: 'cohere',
  }),
  v('SEARCH_REQUIRE_CITATIONS', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Require citations when search allowed',
    safeDefault: 'true',
    aliases: ['WEB_SEARCH_REQUIRE_CITATIONS'],
  }),
  v('SEARCH_REQUIRE_SOURCE_TIMESTAMPS', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Prefer dated sources',
    safeDefault: 'false',
    aliases: ['WEB_SEARCH_REQUIRE_TIMESTAMPS'],
  }),
  v('SEARCH_MAX_QUERIES_PER_REQUEST', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Max search queries per agent turn',
    safeDefault: '6',
    aliases: ['WEB_SEARCH_MAX_QUERIES_PER_REQUEST'],
  }),
  v('SEARCH_MAX_RESULTS_PER_QUERY', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Max results per query',
    safeDefault: '10',
    aliases: ['WEB_SEARCH_MAX_RESULTS_PER_QUERY'],
  }),
  v('SEARCH_DEFAULT_CACHE_TTL_SECONDS', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Search result cache TTL',
    safeDefault: '3600',
    aliases: ['WEB_SEARCH_DEFAULT_CACHE_TTL_SECONDS'],
  }),
  v('SEARCH_ALLOWED_DOMAINS', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'CSV domain allowlist',
    aliases: ['WEB_SEARCH_ALLOWED_DOMAINS'],
  }),
  v('SEARCH_BLOCKED_DOMAINS', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'CSV domain blocklist',
    aliases: ['WEB_SEARCH_BLOCKED_DOMAINS'],
  }),
  v('TAVILY_API_KEY', 'search', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Optional Tavily key when WEB_SEARCH_ENABLED=true',
  }),
  v('TAVILY_SEARCH_ENABLED', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Enable Tavily search adapter',
    safeDefault: 'true',
  }),
  v('TAVILY_EXTRACT_ENABLED', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Enable Tavily extract',
    safeDefault: 'true',
  }),
  v('TAVILY_CRAWL_ENABLED', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Enable Tavily crawl',
    safeDefault: 'true',
  }),
  v('TAVILY_RESEARCH_ENABLED', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Enable Tavily deep research',
    safeDefault: 'true',
  }),
  v('OPENAI_API_KEY', 'search', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Optional OpenAI for web search / fallback generation',
  }),
  v('OPENAI_MODEL', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'OpenAI chat model',
    safeDefault: 'gpt-4o',
    aliases: ['OPENAI_CHAT_MODEL'],
  }),
  v('OPENAI_BASE_URL', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'OpenAI-compatible base URL',
    safeDefault: 'https://api.openai.com/v1',
  }),
  v('OPENAI_WEB_SEARCH_ENABLED', 'search', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Use OpenAI web search when key present',
    safeDefault: 'true',
  }),

  // ─── Optional alternate generation (not primary) ──────────────
  v('XAI_API_KEY', 'ai_optional', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Optional xAI / Grok key',
    aliases: ['GROK_API_KEY'],
  }),
  v('XAI_MODEL', 'ai_optional', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'xAI chat model',
    aliases: ['XAI_CHAT_MODEL'],
  }),
  v('XAI_BASE_URL', 'ai_optional', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'xAI API base',
    safeDefault: 'https://api.x.ai/v1',
  }),
  v('XAI_EMBED_MODEL', 'ai_optional', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Optional xAI embed model',
  }),
  v('XAI_WEB_SEARCH_ENABLED', 'ai_optional', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'xAI web search policy flag',
    safeDefault: 'true',
  }),
  v('XAI_X_SEARCH_ENABLED', 'ai_optional', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'xAI X/Twitter search policy flag',
    safeDefault: 'true',
  }),
  v('XAI_SEARCH_MAX_CALLS', 'ai_optional', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Max xAI search tool calls',
    safeDefault: '5',
  }),
  v('GEMINI_API_KEY', 'ai_optional', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Optional Google Gemini key',
    aliases: ['GOOGLE_AI_API_KEY'],
  }),
  v('GEMINI_MODEL', 'ai_optional', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Gemini model id',
    safeDefault: 'gemini-2.0-flash',
  }),
  v('TRADEOPS_AI_MODE', 'ai_optional', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Legacy xAI mode gate',
    deprecated: true,
    replacement: 'AI_PROVIDER',
  }),
  v('TRADEOPS_AI_DEFAULT_GENERATE', 'ai_optional', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Legacy RAG generate default',
    deprecated: true,
    replacement: 'AI_RUNTIME_ENABLED',
  }),
  v('TRADEOPS_AI_TIMEOUT_MS', 'ai_optional', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Legacy AI timeout',
    deprecated: true,
    replacement: 'COHERE_TIMEOUT_MS',
  }),

  // ─── Platform SaaS billing (Stripe) ───────────────────────────
  v('STRIPE_SECRET_KEY', 'billing', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Stripe secret for platform SaaS billing',
  }),
  v('STRIPE_WEBHOOK_SECRET', 'billing', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Stripe webhook signing secret',
  }),
  v('STRIPE_PRICE_FOUNDER_MONTHLY', 'billing', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Stripe price id founder monthly',
  }),
  v('STRIPE_PRICE_FOUNDER_ANNUAL', 'billing', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Stripe price id founder annual',
  }),
  v('STRIPE_PRICE_PROFESSIONAL_MONTHLY', 'billing', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Stripe price id professional monthly',
  }),
  v('STRIPE_PRICE_PROFESSIONAL_ANNUAL', 'billing', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Stripe price id professional annual',
  }),
  v('STRIPE_PRICE_AGENCY_MONTHLY', 'billing', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Stripe price id agency monthly',
  }),
  v('STRIPE_PRICE_AGENCY_ANNUAL', 'billing', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Stripe price id agency annual',
  }),
  v('STRIPE_PRICE_ENTERPRISE_MONTHLY', 'billing', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Stripe price id enterprise monthly',
  }),
  v('STRIPE_PRICE_ENTERPRISE_ANNUAL', 'billing', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Stripe price id enterprise annual',
  }),

  // ─── Live HTTP / commerce connectors (dev env fallbacks) ──────
  // Production multi-tenant: store in encrypted connector vault per org.
  // Keys match packages/connectors/live-http probeCredentials + env.vendors.template.
  v('SHOPIFY_SHOP_DOMAIN', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Shopify shop domain (prefer vault per tenant)',
  }),
  v('SHOPIFY_ACCESS_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Shopify Admin token (prefer vault per tenant)',
  }),
  v('WOOCOMMERCE_URL', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'WooCommerce store base URL',
  }),
  v('WOOCOMMERCE_CONSUMER_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'WooCommerce REST consumer key',
  }),
  v('WOOCOMMERCE_CONSUMER_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'WooCommerce REST consumer secret',
  }),
  v('BIGCOMMERCE_STORE_HASH', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'BigCommerce store hash',
  }),
  v('BIGCOMMERCE_ACCESS_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'BigCommerce access token',
  }),
  v('AMAZON_SP_CLIENT_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Amazon SP-API client id',
  }),
  v('AMAZON_SP_CLIENT_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Amazon SP-API client secret',
  }),
  v('AMAZON_SP_REFRESH_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Amazon SP-API refresh token',
  }),
  v('EBAY_ACCESS_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'eBay Sell API access token',
  }),
  v('GOOGLE_MERCHANT_ID', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Google Merchant Center account id',
  }),
  v('GOOGLE_MERCHANT_ACCESS_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Google Merchant OAuth access token',
  }),
  v('GOOGLE_MERCHANT_DATA_SOURCE_ID', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Google Merchant data source id',
  }),
  v('PAYPAL_CLIENT_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'PayPal REST client id (merchant)',
  }),
  v('PAYPAL_CLIENT_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'PayPal REST client secret',
  }),
  v('PAYPAL_API_BASE', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'PayPal API base (sandbox vs live)',
    safeDefault: 'https://api-m.sandbox.paypal.com',
  }),
  v('SQUARE_ACCESS_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Square API access token',
  }),
  v('SQUARE_API_BASE', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Square API base URL',
    safeDefault: 'https://connect.squareupsandbox.com',
  }),
  v('EASYPOST_API_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'EasyPost logistics API key',
  }),
  v('SHIPSTATION_API_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'ShipStation API key',
  }),
  v('SHIPSTATION_API_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'ShipStation API secret',
  }),
  v('UPS_CLIENT_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'UPS OAuth client id',
  }),
  v('UPS_CLIENT_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'UPS OAuth client secret',
  }),
  v('FEDEX_CLIENT_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'FedEx API client id',
  }),
  v('FEDEX_CLIENT_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'FedEx API client secret',
  }),
  v('DHL_API_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'DHL API key',
  }),
  v('USPS_CLIENT_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'USPS API client id',
  }),
  v('USPS_CLIENT_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'USPS API client secret',
  }),
  v('CANADA_POST_USERNAME', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Canada Post API username',
  }),
  v('CANADA_POST_PASSWORD', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Canada Post API password',
  }),
  v('SERPAPI_API_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'SerpAPI key (marketplace SERP / competitive)',
  }),
  v('OPENEXCHANGERATES_APP_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Open Exchange Rates app id',
  }),
  v('KEEPA_API_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Keepa Amazon market data key',
  }),
  v('ALIBABA_APP_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Alibaba.com Open Platform app key',
  }),
  v('ALIBABA_APP_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Alibaba.com app secret',
  }),
  v('ALIEXPRESS_APP_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'AliExpress dropshipping app key',
  }),
  v('ALIEXPRESS_APP_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'AliExpress app secret',
  }),
  v('INVENTORY_SOURCE_API_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Inventory Source API key',
  }),
  v('GOOGLE_ADS_DEVELOPER_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Google Ads developer token',
  }),
  v('GOOGLE_ADS_REFRESH_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Google Ads OAuth refresh token',
  }),
  v('META_ACCESS_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Meta Marketing API access token',
  }),
  v('META_AD_ACCOUNT_ID', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Meta ad account id',
  }),
  v('TIKTOK_ACCESS_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'TikTok Marketing API access token',
  }),
  v('TIKTOK_ADVERTISER_ID', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'TikTok advertiser id',
  }),
  v('GA4_PROPERTY_ID', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'GA4 property id (server reporting)',
  }),
  v('GOOGLE_APPLICATION_CREDENTIALS', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Path or JSON for Google service account (GA4/GCP)',
  }),
  v('POSTHOG_API_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'PostHog project API key (tenant analytics optional)',
  }),
  v('POSTHOG_HOST', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'PostHog host URL',
    safeDefault: 'https://app.posthog.com',
  }),
  v('MIXPANEL_PROJECT_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Mixpanel project token',
  }),
  v('MIXPANEL_API_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Mixpanel API secret',
  }),
  v('QUICKBOOKS_ACCESS_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'QuickBooks Online access token',
  }),
  v('QUICKBOOKS_REALM_ID', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'QuickBooks realm / company id',
  }),
  v('XERO_ACCESS_TOKEN', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Xero API access token',
  }),
  v('XERO_TENANT_ID', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Xero tenant id',
  }),
  v('AVALARA_ACCOUNT_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Avalara AvaTax account id',
  }),
  v('AVALARA_LICENSE_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Avalara license key',
  }),
  v('TAXJAR_API_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'TaxJar API key',
  }),
  v('ANTHROPIC_API_KEY', 'ai_optional', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Optional Anthropic key (adapter; not primary runtime)',
  }),
  v('MISTRAL_API_KEY', 'ai_optional', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Optional Mistral key (adapter)',
  }),
  // Enterprise PIM / ERP / PLM (vendor template; vault preferred)
  v('AKENEO_CLIENT_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Akeneo PIM client id',
  }),
  v('AKENEO_CLIENT_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Akeneo PIM client secret',
  }),
  v('AKENEO_BASE_URL', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Akeneo instance base URL',
  }),
  v('SALSIFY_API_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Salsify PIM API key',
  }),
  v('SALSIFY_ORG_ID', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Salsify organization id',
  }),
  v('AUTODESK_CLIENT_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Autodesk Platform Services client id',
  }),
  v('AUTODESK_CLIENT_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Autodesk client secret',
  }),
  v('NETSUITE_ACCOUNT_ID', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Oracle NetSuite account id',
  }),
  v('NETSUITE_CONSUMER_KEY', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'NetSuite consumer key',
  }),
  v('NETSUITE_TOKEN_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'NetSuite token id',
  }),
  v('SAP_CLIENT_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'SAP S/4HANA client id',
  }),
  v('SAP_CLIENT_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'SAP client secret',
  }),
  v('SAP_BASE_URL', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'SAP API base URL',
  }),
  v('INFOR_CLIENT_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Infor CSI client id',
  }),
  v('INFOR_CLIENT_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Infor CSI client secret',
  }),
  v('INFOR_TENANT', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Infor tenant identifier',
  }),
  v('MANHATTAN_CLIENT_ID', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Manhattan WMS client id',
  }),
  v('MANHATTAN_CLIENT_SECRET', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Manhattan WMS client secret',
  }),
  v('WINDCHILL_BASE_URL', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'PTC Windchill base URL',
  }),
  v('WINDCHILL_USER', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Windchill username',
  }),
  v('WINDCHILL_PASSWORD', 'connectors', {
    secret: true,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'tenant_connector_vault',
    description: 'Windchill password',
  }),
  v('TRADEOPS_ALLOW_AUTHORIZED_SOURCING', 'connectors', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Allow authorized sourcing tools',
  }),

  // ─── Ops sync schedulers ──────────────────────────────────────
  v('TRADEOPS_WEBHOOK_DRAIN_MS', 'ops', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Webhook drain interval ms',
    safeDefault: '15000',
  }),
  v('TRADEOPS_CONNECTOR_PROBE_MS', 'ops', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Connector health probe interval ms',
    safeDefault: '300000',
  }),
  v('TRADEOPS_LIVE_SYNC_MS', 'ops', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Live HTTP sync interval ms',
    safeDefault: '900000',
  }),
  v('TRADEOPS_LIVE_SYNC_PROVIDER_COOLDOWN_MS', 'ops', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Per-provider live sync cooldown',
  }),
  v('TRADEOPS_LIVE_SYNC_DISABLED', 'ops', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Disable live HTTP sync scheduler',
  }),
  v('TRADEOPS_OPS_SYNC_DISABLED', 'ops', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Disable ops sync entirely',
  }),

  // ─── Capital / financial gates (packages/config financial-gates.ts) ──
  // Canonical names = FinancialGateKey (process.env[key]). All default OFF except sandbox.
  v('TRADEOPS_CAPITAL_MODE', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Capital product mode switch (UI/product layer)',
  }),
  v('CAPITAL_NETWORK_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Master capital network API gate (legal review)',
    safeDefault: 'false',
  }),
  v('PUBLIC_CAMPAIGNS_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Public campaign listings / solicitation (legal review)',
    safeDefault: 'false',
  }),
  v('INVESTOR_ONBOARDING_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Capital-provider KYC / accreditation onboarding',
    safeDefault: 'false',
  }),
  v('PROFIT_SHARING_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Profit-share funding models (legal review)',
    safeDefault: 'false',
  }),
  v('EQUITY_OFFERINGS_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Equity crowdfunding style offerings (legal review)',
    safeDefault: 'false',
  }),
  v('POOLED_INVESTMENT_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Pooled investment (disabled by default)',
    safeDefault: 'false',
    aliases: ['TRADEOPS_POOLED_INVESTMENT_ENABLED'],
  }),
  v('AUTOMATED_INVESTMENT_ADVICE_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Automated investment advice (must stay off without framework)',
    safeDefault: 'false',
  }),
  v('CAPITAL_CUSTODY_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Platform-controlled investor/campaign balances',
    safeDefault: 'false',
    aliases: ['TRADEOPS_INTERNAL_CUSTODY_ENABLED'],
  }),
  v('DISTRIBUTIONS_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Execute capital/profit distributions',
    safeDefault: 'false',
  }),
  v('MARKETPLACE_CONNECT_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Stripe Connect live onboarding / platform payouts',
    safeDefault: 'false',
  }),
  v('PRIVATE_AGREEMENT_LEDGER_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Private agreement ledger (no public solicitation)',
    safeDefault: 'false',
  }),
  v('CAPITAL_SANDBOX_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Capital sandbox modeling (default ON in financial-gates code)',
    safeDefault: 'true',
  }),
  v('GUARANTEED_RETURNS_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Guaranteed returns (must stay off)',
    safeDefault: 'false',
    aliases: ['TRADEOPS_GUARANTEED_RETURNS_ENABLED'],
  }),
  // Legacy TRADEOPS_* spellings kept as optional platform rows for existing .env files
  v('TRADEOPS_POOLED_INVESTMENT_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Legacy alias for POOLED_INVESTMENT_ENABLED',
    safeDefault: 'false',
    deprecated: true,
    replacement: 'POOLED_INVESTMENT_ENABLED',
  }),
  v('TRADEOPS_GUARANTEED_RETURNS_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Legacy alias for GUARANTEED_RETURNS_ENABLED',
    safeDefault: 'false',
    deprecated: true,
    replacement: 'GUARANTEED_RETURNS_ENABLED',
  }),
  v('TRADEOPS_INTERNAL_CUSTODY_ENABLED', 'capital', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Legacy alias for CAPITAL_CUSTODY_ENABLED',
    safeDefault: 'false',
    deprecated: true,
    replacement: 'CAPITAL_CUSTODY_ENABLED',
  }),

  // ─── Storage / observability / analytics ──────────────────────
  v('TRADEOPS_STORAGE_DIR', 'storage', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Local artifact storage root',
  }),
  v('ARTIFACT_STORAGE_ROOT', 'storage', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'Artifact root override',
  }),
  v('OTEL_EXPORTER_OTLP_ENDPOINT', 'observability', {
    secret: false,
    requiredInProduction: false,
    serverOnly: true,
    storage: 'platform_env',
    description: 'OpenTelemetry OTLP endpoint',
  }),
  v('NEXT_PUBLIC_GA4_ENABLED', 'analytics', {
    secret: false,
    requiredInProduction: false,
    serverOnly: false,
    storage: 'browser_public',
    description: 'Enable GA4 browser tag',
  }),
  v('NEXT_PUBLIC_GA4_MEASUREMENT_ID', 'analytics', {
    secret: false,
    requiredInProduction: false,
    serverOnly: false,
    storage: 'browser_public',
    description: 'GA4 measurement id (public)',
  }),
];

/**
 * Merchant credentials that belong in encrypted tenant connector vault
 * (not global platform .env for multi-tenant production).
 * Derived from live-http probeCredentials + env.vendors.template.
 */
export const TENANT_SCOPED_CREDENTIAL_NAMES = [
  // Commerce channels
  'SHOPIFY_ACCESS_TOKEN',
  'SHOPIFY_SHOP_DOMAIN',
  'WOOCOMMERCE_URL',
  'WOOCOMMERCE_CONSUMER_KEY',
  'WOOCOMMERCE_CONSUMER_SECRET',
  'BIGCOMMERCE_STORE_HASH',
  'BIGCOMMERCE_ACCESS_TOKEN',
  'AMAZON_SP_CLIENT_ID',
  'AMAZON_SP_CLIENT_SECRET',
  'AMAZON_SP_REFRESH_TOKEN',
  'EBAY_ACCESS_TOKEN',
  'GOOGLE_MERCHANT_ID',
  'GOOGLE_MERCHANT_ACCESS_TOKEN',
  'GOOGLE_MERCHANT_DATA_SOURCE_ID',
  // Merchant payments
  'PAYPAL_CLIENT_ID',
  'PAYPAL_CLIENT_SECRET',
  'SQUARE_ACCESS_TOKEN',
  // Logistics
  'EASYPOST_API_KEY',
  'SHIPSTATION_API_KEY',
  'SHIPSTATION_API_SECRET',
  'UPS_CLIENT_ID',
  'UPS_CLIENT_SECRET',
  'FEDEX_CLIENT_ID',
  'FEDEX_CLIENT_SECRET',
  'DHL_API_KEY',
  'USPS_CLIENT_ID',
  'USPS_CLIENT_SECRET',
  'CANADA_POST_USERNAME',
  'CANADA_POST_PASSWORD',
  // Market intelligence
  'SERPAPI_API_KEY',
  'OPENEXCHANGERATES_APP_ID',
  'KEEPA_API_KEY',
  'ALIBABA_APP_KEY',
  'ALIBABA_APP_SECRET',
  'ALIEXPRESS_APP_KEY',
  'ALIEXPRESS_APP_SECRET',
  'INVENTORY_SOURCE_API_KEY',
  // Ads / analytics (tenant)
  'GOOGLE_ADS_DEVELOPER_TOKEN',
  'GOOGLE_ADS_REFRESH_TOKEN',
  'META_ACCESS_TOKEN',
  'META_AD_ACCOUNT_ID',
  'TIKTOK_ACCESS_TOKEN',
  'TIKTOK_ADVERTISER_ID',
  'GA4_PROPERTY_ID',
  'GOOGLE_APPLICATION_CREDENTIALS',
  'POSTHOG_API_KEY',
  'MIXPANEL_PROJECT_TOKEN',
  'MIXPANEL_API_SECRET',
  // Accounting / tax
  'QUICKBOOKS_ACCESS_TOKEN',
  'QUICKBOOKS_REALM_ID',
  'XERO_ACCESS_TOKEN',
  'XERO_TENANT_ID',
  'AVALARA_ACCOUNT_ID',
  'AVALARA_LICENSE_KEY',
  'TAXJAR_API_KEY',
  // Enterprise PIM / ERP / PLM / WMS
  'AKENEO_CLIENT_ID',
  'AKENEO_CLIENT_SECRET',
  'AKENEO_BASE_URL',
  'SALSIFY_API_KEY',
  'SALSIFY_ORG_ID',
  'AUTODESK_CLIENT_ID',
  'AUTODESK_CLIENT_SECRET',
  'NETSUITE_ACCOUNT_ID',
  'NETSUITE_CONSUMER_KEY',
  'NETSUITE_TOKEN_ID',
  'SAP_CLIENT_ID',
  'SAP_CLIENT_SECRET',
  'SAP_BASE_URL',
  'INFOR_CLIENT_ID',
  'INFOR_CLIENT_SECRET',
  'INFOR_TENANT',
  'MANHATTAN_CLIENT_ID',
  'MANHATTAN_CLIENT_SECRET',
  'WINDCHILL_BASE_URL',
  'WINDCHILL_USER',
  'WINDCHILL_PASSWORD',
] as const;

/** Alias → canonical name map for migration. */
export const ENV_ALIASES: Record<string, string> = {
  COHERE_MODEL: 'COHERE_CHAT_MODEL',
  COHERE_REQUEST_TIMEOUT_MS: 'COHERE_TIMEOUT_MS',
  RETRIEVAL_ENABLED: 'COHERE_RETRIEVAL_ENABLED',
  GROK_API_KEY: 'XAI_API_KEY',
  XAI_CHAT_MODEL: 'XAI_MODEL',
  OPENAI_CHAT_MODEL: 'OPENAI_MODEL',
  GOOGLE_AI_API_KEY: 'GEMINI_API_KEY',
  WEB_SEARCH_PROVIDER: 'SEARCH_PROVIDER_PRIMARY',
  WEB_SEARCH_REQUIRE_CITATIONS: 'SEARCH_REQUIRE_CITATIONS',
  WEB_SEARCH_REQUIRE_TIMESTAMPS: 'SEARCH_REQUIRE_SOURCE_TIMESTAMPS',
  WEB_SEARCH_MAX_QUERIES_PER_REQUEST: 'SEARCH_MAX_QUERIES_PER_REQUEST',
  WEB_SEARCH_MAX_RESULTS_PER_QUERY: 'SEARCH_MAX_RESULTS_PER_QUERY',
  WEB_SEARCH_DEFAULT_CACHE_TTL_SECONDS: 'SEARCH_DEFAULT_CACHE_TTL_SECONDS',
  WEB_SEARCH_ALLOWED_DOMAINS: 'SEARCH_ALLOWED_DOMAINS',
  WEB_SEARCH_BLOCKED_DOMAINS: 'SEARCH_BLOCKED_DOMAINS',
  TRADEOPS_AI_MODE: 'AI_PROVIDER',
  TRADEOPS_AI_TIMEOUT_MS: 'COHERE_TIMEOUT_MS',
  TRADEOPS_POOLED_INVESTMENT_ENABLED: 'POOLED_INVESTMENT_ENABLED',
  TRADEOPS_GUARANTEED_RETURNS_ENABLED: 'GUARANTEED_RETURNS_ENABLED',
  TRADEOPS_INTERNAL_CUSTODY_ENABLED: 'CAPITAL_CUSTODY_ENABLED',
};

export function listManifestSecrets(): string[] {
  return PLATFORM_ENV_MANIFEST.filter((row) => row.secret).map((row) => row.name);
}

export function listRequiredProductionEnv(): string[] {
  return PLATFORM_ENV_MANIFEST.filter((row) => row.requiredInProduction).map((row) => row.name);
}

export function resolveEnvAlias(name: string): string {
  return ENV_ALIASES[name] ?? name;
}

export function environmentManifestPublicStatus(
  env: NodeJS.ProcessEnv | Record<string, string | undefined> = process.env,
) {
  const present = (name: string) => Boolean((env[name] ?? '').toString().trim());
  const rows = PLATFORM_ENV_MANIFEST.map((row) => ({
    name: row.name,
    subsystem: row.subsystem,
    secret: row.secret,
    requiredInProduction: row.requiredInProduction,
    configured: present(row.name) || Boolean(row.aliases?.some((a) => present(a))),
    storage: row.storage,
    deprecated: Boolean(row.deprecated),
  }));
  const missingRequiredProd =
    env.NODE_ENV === 'production'
      ? rows.filter((r) => r.requiredInProduction && !r.configured).map((r) => r.name)
      : [];
  return {
    totalManifest: PLATFORM_ENV_MANIFEST.length,
    configured: rows.filter((r) => r.configured).length,
    missingRequiredProduction: missingRequiredProd,
    architecture: {
      aiPrimary: 'cohere',
      searchOwnedBy: 'tradeops_search_manager',
      tenantSecrets: 'encrypted_connector_vault',
      compromisedKeyPolicy: 'rotate_immediately_never_reuse_chat_pasted_keys',
    },
    ai: {
      provider: (env.AI_PROVIDER ?? 'cohere').toString(),
      cohereKeyConfigured: present('COHERE_API_KEY'),
      webSearchEnabled: present('WEB_SEARCH_ENABLED')
        ? ['1', 'true', 'yes', 'on'].includes(String(env.WEB_SEARCH_ENABLED).toLowerCase())
        : false,
      tavilyConfigured: present('TAVILY_API_KEY'),
      openaiConfigured: present('OPENAI_API_KEY'),
      xaiConfigured: present('XAI_API_KEY') || present('GROK_API_KEY'),
    },
    tenantScopedNote:
      'Merchant Shopify/Amazon/EasyPost/etc. tokens belong in encrypted connector vault, not global .env for multi-tenant production.',
    aliases: ENV_ALIASES,
    rows,
  };
}
