import type { CanonicalProductOffer } from '@tradeops/connector-core';

/** Explicit FIXTURE catalog — not live supplier API data. */
export const FIXTURE_SUPPLIER_CATALOG: CanonicalProductOffer[] = [
  {
    externalId: 'fs-desk-organizer-01',
    sourcePlatform: 'fixture-supplier',
    title: 'Modular Bamboo Desk Organizer',
    description: 'Stackable desk organizer for home office. Sustainable bamboo.',
    category: 'Home Office',
    supplierName: 'Fixture Supply Co',
    supplierExternalId: 'sup-fixture-001',
    supplierCostMinor: 1250,
    shippingCostMinor: 350,
    currency: 'USD',
    inventoryQuantity: 480,
    rating: 4.6,
    reviewCount: 214,
    collectedAt: new Date().toISOString(),
    dataConfidence: 0.85,
  },
  {
    externalId: 'fs-water-bottle-02',
    sourcePlatform: 'fixture-supplier',
    title: 'Insulated Stainless Water Bottle 32oz',
    description: 'Double-wall insulated bottle. BPA-free lid.',
    category: 'Sports',
    supplierName: 'Fixture Supply Co',
    supplierExternalId: 'sup-fixture-001',
    supplierCostMinor: 980,
    shippingCostMinor: 420,
    currency: 'USD',
    inventoryQuantity: 1200,
    rating: 4.4,
    reviewCount: 890,
    collectedAt: new Date().toISOString(),
    dataConfidence: 0.9,
  },
  {
    externalId: 'fs-led-strip-03',
    sourcePlatform: 'fixture-supplier',
    title: 'USB LED Strip Light Kit with Remote',
    description: 'RGB LED strip for rooms. Includes remote and USB power.',
    category: 'Electronics',
    supplierName: 'Fixture Lighting OEM',
    supplierExternalId: 'sup-fixture-002',
    supplierCostMinor: 650,
    shippingCostMinor: 280,
    currency: 'USD',
    inventoryQuantity: 2200,
    rating: 4.1,
    reviewCount: 1520,
    collectedAt: new Date().toISOString(),
    dataConfidence: 0.8,
  },
  {
    externalId: 'fs-yoga-mat-04',
    sourcePlatform: 'fixture-supplier',
    title: 'Non-Slip TPE Yoga Mat 6mm',
    description: 'Lightweight yoga mat with carry strap.',
    category: 'Fitness',
    supplierName: 'Fixture Supply Co',
    supplierExternalId: 'sup-fixture-001',
    supplierCostMinor: 1100,
    shippingCostMinor: 500,
    currency: 'USD',
    inventoryQuantity: 340,
    rating: 4.5,
    reviewCount: 430,
    collectedAt: new Date().toISOString(),
    dataConfidence: 0.82,
  },
  {
    externalId: 'fs-blocked-weapon-99',
    sourcePlatform: 'fixture-supplier',
    title: 'Tactical Weapon Holster Training Kit',
    description: 'Training accessory resembling firearm holster. Policy test SKU.',
    category: 'Restricted Test',
    supplierName: 'Fixture Risk Samples',
    supplierExternalId: 'sup-fixture-risk',
    supplierCostMinor: 2000,
    shippingCostMinor: 400,
    currency: 'USD',
    inventoryQuantity: 50,
    rating: 3.2,
    reviewCount: 12,
    collectedAt: new Date().toISOString(),
    dataConfidence: 0.7,
  },
];
